version: "3.7"
name: gameplan
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash -c "wget -O /workspace/init.sh https://github.com/test-app-x/gameplan/blob/main/docker/init.sh && chmod +x /workspace/init.sh && bash /workspace/init.sh"
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - ..:/workspace  # Maps the project root
    ports:
      - 8009:8000
      - 9009:9000

volumes:
  mariadb-data:
